// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXIWu653puJC5TdWS5oDb3h4mURPfBZDo',
    appId: '1:17755701300:web:100caf74a936c1c4a8ca61',
    messagingSenderId: '17755701300',
    projectId: 'task-manager-app-3bfa3',
    authDomain: 'task-manager-app-3bfa3.firebaseapp.com',
    storageBucket: 'task-manager-app-3bfa3.firebasestorage.app',
    measurementId: 'G-SYF05K3REP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3M_PJjLIkpHrMkSBu3rN-xAnDySzHZrs',
    appId: '1:17755701300:android:cabca59a7eeb052ca8ca61',
    messagingSenderId: '17755701300',
    projectId: 'task-manager-app-3bfa3',
    storageBucket: 'task-manager-app-3bfa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLFuQdRdGmEBXsfvOVfn4ZtE4340FPqkk',
    appId: '1:17755701300:ios:9dce644ec8be2182a8ca61',
    messagingSenderId: '17755701300',
    projectId: 'task-manager-app-3bfa3',
    storageBucket: 'task-manager-app-3bfa3.firebasestorage.app',
    iosBundleId: 'com.example.bonusAssignment',
  );
}
